//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMen.MultiMerchant.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaoMen.MultiMerchant.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_0 {
            get {
                return ResourceManager.GetString("Error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统异常.
        /// </summary>
        public static string Error_1000 {
            get {
                return ResourceManager.GetString("Error_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名/密码 不能为空.
        /// </summary>
        public static string Error_10001 {
            get {
                return ResourceManager.GetString("Error_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不存在.
        /// </summary>
        public static string Error_10002 {
            get {
                return ResourceManager.GetString("Error_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不正确.
        /// </summary>
        public static string Error_10003 {
            get {
                return ResourceManager.GetString("Error_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户不存在.
        /// </summary>
        public static string Error_10004 {
            get {
                return ResourceManager.GetString("Error_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken已过期.
        /// </summary>
        public static string Error_10005 {
            get {
                return ResourceManager.GetString("Error_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken不正确.
        /// </summary>
        public static string Error_10006 {
            get {
                return ResourceManager.GetString("Error_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户已禁用.
        /// </summary>
        public static string Error_10007 {
            get {
                return ResourceManager.GetString("Error_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建数据失败.
        /// </summary>
        public static string Error_1001 {
            get {
                return ResourceManager.GetString("Error_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新数据失败.
        /// </summary>
        public static string Error_1002 {
            get {
                return ResourceManager.GetString("Error_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除数据失败.
        /// </summary>
        public static string Error_1003 {
            get {
                return ResourceManager.GetString("Error_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已由其它人修改，请刷新后重试.
        /// </summary>
        public static string Error_1004 {
            get {
                return ResourceManager.GetString("Error_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据校验失败.
        /// </summary>
        public static string Error_1005 {
            get {
                return ResourceManager.GetString("Error_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件上传失败.
        /// </summary>
        public static string Error_1006 {
            get {
                return ResourceManager.GetString("Error_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API返回失败.
        /// </summary>
        public static string Error_1007 {
            get {
                return ResourceManager.GetString("Error_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用API失败.
        /// </summary>
        public static string Error_1008 {
            get {
                return ResourceManager.GetString("Error_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码不正确.
        /// </summary>
        public static string Error_1009 {
            get {
                return ResourceManager.GetString("Error_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机验证码不正确.
        /// </summary>
        public static string Error_1010 {
            get {
                return ResourceManager.GetString("Error_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map数据失败.
        /// </summary>
        public static string Error_1011 {
            get {
                return ResourceManager.GetString("Error_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求无效（数据验证未通过）.
        /// </summary>
        public static string Error_400 {
            get {
                return ResourceManager.GetString("Error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份验证未通过（未登录）.
        /// </summary>
        public static string Error_401 {
            get {
                return ResourceManager.GetString("Error_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止访问（无权限）.
        /// </summary>
        public static string Error_403 {
            get {
                return ResourceManager.GetString("Error_403", resourceCulture);
            }
        }
    }
}
